print:
  max-retry: 3 # 最大重试次数
  queue:
    offer-timeout: 5  # 设置等待5秒
# 服务端口配置
server:
  port: 8080
# 日志配置
logging:
  file:
    name: logs/print-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30